#!/usr/bin/env bash

# Created by MasterRoot24 (Joe Nyland)
# https://github.com/MasterRoot24/git-vommit
# As the title suggests, this plugin makes Git vomit, so you learn the hard way *not* to type `git vommit`.

main() {
  echo $(git log -p --oneline --binary)
}

main
